### ISSUE TITLE
Error loading 'colors' module

### ISSUE THREAD

**Issue by jinglerobs** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#1]
Issue while executing the '$node apicia.js' command. Error loading 'colors' module

**Comment by phillip3-automated** [comment]
I have a fix for that that I will be pushing out shortly.

**Comment by ChrisPhillips-cminion** [comment]
Please try with the lastest code

**Comment by ChrisPhillips-cminion** [comment]
As a second issue has been raised i assume you have got further. Can I close this?

**Comment by jinglerobs** [comment]
Yes, please close the first issue for colors.

**Comment by ChrisPhillips-cminion** [comment]
Thanks
