### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by drichards-levtech** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#11]
I had to manually manually install the following to get it to run:
npm install fs.extra sprintf

OS: CentOS 7.4.1708  {"os":"linux","arch":"x64"}
npm --version     5.5.1
node --version  v6.11.5

**Comment by ChrisPhillips-cminion** [comment]
Thanks, added that to the package json, i obviously over pruned and had those installed as global on my laptop

**Comment by ChrisPhillips-cminion** [comment]
Fix pushed

**Comment by ChrisPhillips-cminion** [comment]
Please reopen if this problem is seen again
