### ISSUE TITLE
ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by usuresh80** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#15]
getting below errror while running this  js 

D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master>node apicia.js
? API Connect Management Server? X.X.X.X
? Username test
? Password [hidden]
? Do you want to show all Policies? Yes
√ Logging in...
√ Fetching organizations
? Please select the target organization: Org-dev
√ Fetching catalogs for organization: catalogue-dev
? Please select the target catalog: (Press <space> to select, <a> to toggle all,
? Please select the target catalog:
? Please select which data you wish to show: Policy / Service Details 1, Policy
 / Service Details 2, API, Product
? Do you want to save this config: Yes
? Where do you want the config file to be saved 
Config saved to 

Results of analysis:
────────────────────────────────────────

D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master\lib\functions.js:24
        o && console.error(o), config.debug && console.error("Changing directory
 to: " + e), process.chdir(e)

                     ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\functions.js:24:102
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by ChrisPhillips-cminion** [comment]
Couple of quick questions
1) Does it work if you say you do not want to save the config.
2) Does it work if you try the beta stream, i was about to merge it but am now going to hold off..
3) Did you set the config file name

**Comment by usuresh80** [comment]
Here are my updates 
1.Does it work if you say you do not want to save the config. - **No did not work** 
2.Does it work if you try the beta stream, i was about to merge it but am now going to hold off.. UPDATE NOW MERGED
3.Did you set the config file name

**Comment by usuresh80** [comment]
3.Did you set the config file name  - Yes It worked with config file , But Now I am getting errors , after running command

https://ue00comwbd01.bjw2k.asg/wcs/resources/store/10201/BjsPayPageDetailsDataBe
an/payment/PayPageDet?responseFormat=application/json

WCS_HostAddress)/wcs/resources/store/10201/cart/@self/renew_order_items

WCS_HostAddress)/wcs/resources/store/10201/cart/@self

WCS_HostAddress)/wcs/resources/store/10201/online_store?responseFormat=json

WCS_HostAddress)/wcs/resources/store/10201/orderCapture/cart/view_bjsOnlineCart?
orderId=
BjsRenewOrder_var.body.orderId)&response=application/json
TypeError: Cannot read property 'value' of undefined
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:137:71
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\index.js:10:13
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\node_modules\async\dist\async.js:3686:9

    at eachOfArrayLike (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\
APIConnect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dis
t\async.js:941:9)
    at eachOf (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnec
t-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\async.j
s:991:5)
    at _parallel (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APICon
nect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\asyn
c.js:3685:5)
    at Object.parallelLimit [as parallel] (D:\Temp\api-dependency\APIConnect-Imp
actAnalysis-master\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\nod
e_modules\async\dist\async.js:3765:3)
    at Array.forEachThen (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-maste
r\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\index.js:15:11)
    at replaceVariables (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master
\APIConnect-ImpactAnalysis-master\lib\parseYaml.js:128:21)
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:100:17
D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master\lib\getData.js:70
                                if (e) throw e;
                                       ^

TypeError: Cannot read property 'value' of undefined
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:137:71
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\index.js:10:13
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\node_modules\async\dist\async.js:3686:9

    at eachOfArrayLike (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\
APIConnect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dis
t\async.js:941:9)
    at eachOf (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnec
t-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\async.j
s:991:5)
    at _parallel (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APICon
nect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\asyn
c.js:3685:5)
    at Object.parallelLimit [as parallel] (D:\Temp\api-dependency\APIConnect-Imp
actAnalysis-master\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\nod
e_modules\async\dist\async.js:3765:3)
    at Array.forEachThen (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-maste
r\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\index.js:15:11)
    at replaceVariables (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master
\APIConnect-ImpactAnalysis-master\lib\parseYaml.js:128:21)
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:100:17

**Comment by ChrisPhillips-cminion** [comment]
Could you please pull hte latest code and give me the new error message, then the stack traces can line up with my code.

**Comment by usuresh80** [comment]
Here it is 

- Downloading Product aws-dev1:membershipenrollment:1.0.0 this may take a few mi
- Downloading Product aws-dev1:bjsshoppingpathproduct:1.0.0 this may take a few
√ Downloading Product aws-dev1:membershipenrollment:1.0.0 this may take a few mi
nutes...
\ Downloading Product aws-dev1:bjsshoppingpathproduct:1.0.0 this may take a few
√ Downloading Product aws-dev1:bjsshoppingpathproduct:1.0.0 this may take a few
minutes...
TypeError: Cannot read property 'value' of undefined
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:148:71
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\index.js:10:13
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\node_modules\async\dist\async.js:3686:9

    at eachOfArrayLike (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\
APIConnect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dis
t\async.js:941:9)
    at eachOf (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnec
t-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\async.j
s:991:5)
    at _parallel (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APICon
nect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\asyn
c.js:3685:5)
    at Object.parallelLimit [as parallel] (D:\Temp\api-dependency\APIConnect-Imp
actAnalysis-master\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\nod
e_modules\async\dist\async.js:3765:3)
    at Array.forEachThen (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-maste
r\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\index.js:15:11)
    at replaceVariables (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master
\APIConnect-ImpactAnalysis-master\lib\parseYaml.js:142:21)
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:117:17
D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master\lib\getData.js:64
                                if (e) throw e;
                                       ^

TypeError: Cannot read property 'value' of undefined
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:148:71
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\index.js:10:13
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\node_modules\foreachthen\node_modules\async\dist\async.js:3686:9

    at eachOfArrayLike (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\
APIConnect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dis
t\async.js:941:9)
    at eachOf (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnec
t-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\async.j
s:991:5)
    at _parallel (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APICon
nect-ImpactAnalysis-master\node_modules\foreachthen\node_modules\async\dist\asyn
c.js:3685:5)
    at Object.parallelLimit [as parallel] (D:\Temp\api-dependency\APIConnect-Imp
actAnalysis-master\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\nod
e_modules\async\dist\async.js:3765:3)
    at Array.forEachThen (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-maste
r\APIConnect-ImpactAnalysis-master\node_modules\foreachthen\index.js:15:11)
    at replaceVariables (D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master
\APIConnect-ImpactAnalysis-master\lib\parseYaml.js:142:21)
    at D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-Impact
Analysis-master\lib\parseYaml.js:117:17

D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master>
D:\Temp\api-dependency\APIConnect-ImpactAnalysis-master\APIConnect-ImpactAnalysi
s-master>

**Comment by ChrisPhillips-cminion** [comment]
Please try the beta branch, if that works I will merge.

**Comment by ChrisPhillips-cminion** [comment]
Any Update?

**Comment by usuresh80** [comment]
I did not get any errors with Beta code , But will do some more testing and confirm

**Comment by ChrisPhillips-cminion** [comment]
Close as no update in 5days, if you find an issue please raise a new issue!
