### ISSUE TITLE
Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by sebastiansutter** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#19]
[accountapis_1.0.0.yaml.txt](https://github.com/ChrisPhillips-cminion/APIConnect-ImpactAnalysis/files/2410765/accountapis_1.0.0.yaml.txt)
[accountservice_1.0.0.yaml.txt](https://github.com/ChrisPhillips-cminion/APIConnect-ImpactAnalysis/files/2410766/accountservice_1.0.0.yaml.txt)

I tested on the tech sales stack with a catalog that has one Product with one API and the config below. Getting:
$ node apicia.js --load .apicia 
/Users/Sebastian/Documents/apic/APIConnect-ImpactAnalysis-beta/lib/parseYaml.js:24
        apiName = jsonFile.info['x-ibm-name'],
                                        ^

TypeError: Cannot read property 'info' of undefined
    at parseYaml (/Users/Sebastian/Documents/apic/APIConnect-ImpactAnalysis-beta/lib/parseYaml.js:24:27)

{
  "catalog": {
    "Test": {
      "displayName": "Test",
      "machineName": "test"
    }
  },
  "applicationDirectory": "/Users/Sebastian/Documents/apic/APIConnect-ImpactAnalysis-beta",
  "realm": "provider/default-idp-2",
  "password": "XXX=",
  "username": "sutter@de.ibm.com",
  "version": "v2018",
  "server": "api-manager-ui.apic-tech-sales.us-east.containers.appdomain.cloud",
  "accessToken": "Bearer ey..",
  "organization": "sebastians-org",
  "dataType": "Policies",
  "displaySchema": [
    "API",
    "Product"
  ]

**Comment by ChrisPhillips-cminion** [comment]
Fixed pushed, please test again and let me know if it is working  (or not)

**Comment by sebastiansutter** [comment]
works now, thanks
